export interface NewsItem {
  story_id: string;
  date: string;
  vendor: string;
  /** Set when a story prominently involves two companies (e.g. Apple+Google for Gemini-Siri,
   *  Meta+AWS for Graviton5 deal). Empty / undefined for single-vendor stories. */
  secondary_vendor?: string;
  headline: string;
  headline_he: string;
  summary: string;
  summary_he: string;
  detail?: string;
  detail_he?: string;
  // Per-story TTS audio (edge-tts → MP3 on GH Pages). Two flavours so
  // what-you-hear matches what-you-see: summary version for homepage
  // cards (short), detail version for the /story?id=… detail page (long).
  // Both prefix the headline before the body. Optional — older stories
  // before the per-card-Listen rollout won't have these set.
  summary_audio_url?: string;
  summary_audio_url_he?: string;
  detail_audio_url?: string;
  detail_audio_url_he?: string;
  urls: string[];
  source_count: number;
  published_date: string;
  og_image?: string;
  tldr: string[];
  tldr_he: string[];
  community_pulse: string;
  community_pulse_he: string;
  community_urls: string[];
  trending_topics: TrendingTopic[];
  people_highlights: PersonHighlight[];
  top_reddit: RedditPost[];
}

export interface TrendingTopic {
  label: string;
  url?: string;
}

export interface PersonHighlight {
  name: string;
  handle: string;
  org: string;
  role: string;
  post: string;
  url?: string;
  engagement?: string;
  why?: string;
}

export interface RedditPost {
  subreddit: string;
  subreddit_icon_url?: string;
  title: string;
  title_he?: string;
  body?: string;
  body_he?: string;
  score: number;
  num_comments?: number;
  url: string;
  date?: string;
}

export interface CommunityPulseItem {
  headline: string;
  body: string;
  heat: "hot" | "warm" | "mild";
  source_url: string;
  source_label: string;
  related_vendor: string;
  related_person: string;
  og_image?: string;
  /** ISO date extracted from URL path (/YYYY/MM/DD/) when available, else absent. */
  date?: string;
}

export interface YouTubeVideo {
  // Pipeline produces news-item-shaped objects: title lives in `headline`,
  // url in `urls[0]`, channel/views/duration as structured fields after the
  // 2026-05-10 ingest update. Older shape (`title`, `url`, `views: string`)
  // is kept optional for backward compat with archive days.
  headline?: string;
  title?: string;
  url?: string;
  urls?: string[];
  channel?: string;
  views?: number | string;
  views_text?: string;
  duration_seconds?: number;
  duration_text?: string;
  thumbnail?: string;
  date?: string;
  published_date?: string;
  description?: string;
  summary?: string;
  vendor?: string;
  paired_with_story_id?: string;
}

export interface ChannelLatestVideo {
  channel: string;
  channel_id: string;
  title: string;
  url: string;
  published_at: string;
  thumbnail?: string;
}

export interface GitHubRepo {
  name: string;
  url: string;
  description: string;
  stars: string;
  language: string;
  date?: string;
}

export interface DayData {
  date: string;
  stories: NewsItem[];
  tldr: string[];
  tldr_he: string[];
  // TLDR audio (text-to-speech) — generated by publish_data.py via edge-tts.
  // Optional: empty/undefined when audio gen failed or wasn't run yet.
  tldr_audio_url?: string;
  tldr_audio_url_he?: string;
  // Explicit bullet→story binding from merger pipeline. bullet_story_ids[i]
  // is the story_id that tldr[i]/tldr_he[i] refers to. When present and valid,
  // BriefingPage uses it directly and skips the keyword-scorer fallback (which
  // was getting confused by vendor names appearing in someone else's product
  // names — e.g. "typosquatted 'OpenAI Privacy Filter' on Hugging Face" was
  // routed to OpenAI's shopping-ads story before this field existed).
  bullet_story_ids?: string[];
  community_pulse: string;
  community_pulse_he: string;
  community_pulse_items: CommunityPulseItem[];
  community_pulse_items_he: { headline_he: string; body_he: string }[];
  community_urls: string[];
  trending_topics: TrendingTopic[];
  people_highlights: PersonHighlight[];
  people_highlights_he: { post_he: string; why_he: string }[];
  top_reddit: RedditPost[];
  youtube: YouTubeVideo[];
  youtube_channel_latest?: ChannelLatestVideo[];
  github: GitHubRepo[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  twitter: any;
  twitter_descs_he?: string[];
  // LLM-translated Hebrew descriptions for top YouTube videos. Capped at the
  // pre-2026-05-10 display ceiling of 12 by the merger; aligned by URL to
  // `youtube[i]` after publish_data.py's per-channel cap remap.
  youtube_descs_he?: string[];
}
