import DatePageClient from "./DatePageClient";

// Pre-render archive dates at build time; unknown dates fall through to
// the Home page which reads the URL path as a client-side fallback
export async function generateStaticParams() {
  try {
    const apiBase = process.env.NEXT_PUBLIC_API_URL || "https://aibriefing.dev";
    // Use the canonical /data/archive.json (kept current by local-cycle [3b]),
    // NOT /api/archive — the latter is generated by the ingest lambda and has
    // been frozen at 2026-05-26, so the last ~10 days of date pages were never
    // statically generated and fell back to a client-only shell (breaking
    // deep-link scroll + OG/SEO for recent stories). archive.json is
    // {"dates": [...]} newest-first. (2026-06-05)
    const res = await fetch(`${apiBase}/data/archive.json`, { next: { revalidate: 0 } });
    if (res.ok) {
      const data = await res.json();
      const dates: string[] = data?.dates || [];
      if (dates.length > 0) {
        return dates.map((date: string) => ({ date }));
      }
    }
  } catch {
    // Build-time fetch may fail; fall back to known dates
  }
  return [{ date: "2026-04-06" }];
}

export default function DatePage({
  params,
}: {
  params: Promise<{ date: string }>;
}) {
  return <DatePageClient params={params} />;
}
