"""Curated AI YouTube channels + Spotify podcasts.

Mirrors the CHANNELS list in web/src/app/media/page.tsx so the static report
shows the same recommendations as the website. Edits to this list should be
made in BOTH places (until we extract a JSON source of truth).
"""

CHANNELS: list[dict] = [
    # ── YouTube — Hebrew ───────────────────────────
    {"name": "CloudAI Hebrew", "name_he": "CloudAI עברית",
     "desc": "AI tutorials & news in Hebrew",
     "desc_he": "הדרכות וחדשות AI בעברית",
     "url": "https://www.youtube.com/@CloudAI_Hebrew",
     "platform": "youtube", "lang": "he"},
    {"name": "TrashTech News", "name_he": "טראשטק",
     "desc": "Tech industry gossip, AI & startup news",
     "desc_he": "גוסיפ טק, חדשות AI וסטארטאפים",
     "url": "https://www.youtube.com/@TrashTechNews",
     "platform": "youtube", "lang": "he"},
    {"name": "yuv-ai", "name_he": "yuv-ai",
     "desc": "AI skills, Claude Code, and dev tools",
     "desc_he": "כישורי AI, Claude Code וכלי פיתוח",
     "url": "https://www.youtube.com/@yuv-ai",
     "platform": "youtube", "lang": "he"},
    # ── YouTube — English: Official ────────────────
    {"name": "Claude", "name_he": "Claude",
     "desc": "Official Anthropic channel — Claude demos & updates",
     "desc_he": "הערוץ הרשמי של Anthropic — הדגמות ועדכוני Claude",
     "url": "https://www.youtube.com/@claude",
     "platform": "youtube", "lang": "en"},
    {"name": "Google Cloud Tech", "name_he": "Google Cloud Tech",
     "desc": "Gemini, Vertex AI, ADK & cloud AI demos",
     "desc_he": "Gemini, Vertex AI, ADK והדגמות AI בענן",
     "url": "https://www.youtube.com/@GoogleCloudTech",
     "platform": "youtube", "lang": "en"},
    {"name": "Google for Developers", "name_he": "Google for Developers",
     "desc": "Google AI APIs, ADK, and developer tools",
     "desc_he": "ממשקי AI של גוגל, ADK וכלי פיתוח",
     "url": "https://www.youtube.com/@GoogleDevelopers",
     "platform": "youtube", "lang": "en"},
    {"name": "OpenAI", "name_he": "OpenAI",
     "desc": "GPT, Codex, Sora demos & research talks",
     "desc_he": "הדגמות GPT, Codex, Sora ושיחות מחקר",
     "url": "https://www.youtube.com/@OpenAI",
     "platform": "youtube", "lang": "en"},
    {"name": "Amazon Web Services", "name_he": "Amazon Web Services",
     "desc": "Bedrock, AI agents, serverless & cloud tutorials",
     "desc_he": "Bedrock, סוכני AI, serverless והדרכות ענן",
     "url": "https://www.youtube.com/@amazonwebservices",
     "platform": "youtube", "lang": "en"},
    # ── YouTube — English: Creators ────────────────
    {"name": "Fireship", "name_he": "Fireship",
     "desc": "Fast-paced AI & dev news in 100 seconds",
     "desc_he": "חדשות AI ופיתוח בקצב מהיר",
     "url": "https://www.youtube.com/@Fireship",
     "platform": "youtube", "lang": "en"},
    {"name": "Matt Wolfe", "name_he": "Matt Wolfe",
     "desc": "Weekly AI tool roundups & news",
     "desc_he": "סקירת כלי AI שבועית וחדשות",
     "url": "https://www.youtube.com/@mreflow",
     "platform": "youtube", "lang": "en"},
    {"name": "Two Minute Papers", "name_he": "Two Minute Papers",
     "desc": "AI research explained — what a time to be alive!",
     "desc_he": "מחקרי AI מוסברים בקצרה",
     "url": "https://www.youtube.com/@TwoMinutePapers",
     "platform": "youtube", "lang": "en"},
    {"name": "Theo - t3.gg", "name_he": "Theo - t3.gg",
     "desc": "Dev tools, AI coding, and web dev takes",
     "desc_he": "כלי פיתוח, AI קוד ועולם הווב",
     "url": "https://www.youtube.com/@t3dotgg",
     "platform": "youtube", "lang": "en"},
    {"name": "AI Explained", "name_he": "AI Explained",
     "desc": "Deep-dive analysis of AI breakthroughs",
     "desc_he": "ניתוחים מעמיקים של פריצות דרך ב-AI",
     "url": "https://www.youtube.com/@aiexplained-official",
     "platform": "youtube", "lang": "en"},
    {"name": "Greg Isenberg", "name_he": "Greg Isenberg",
     "desc": "AI startups, products & business ideas",
     "desc_he": "סטארטאפים, מוצרים ורעיונות עסקיים עם AI",
     "url": "https://www.youtube.com/@GregIsenberg",
     "platform": "youtube", "lang": "en"},
    # ── Podcasts — Hebrew ──────────────────────────
    {"name": "בזמן שעבדתם", "name_he": "בזמן שעבדתם",
     "desc": "News you missed while working — AI, tech & culture",
     "desc_he": "חדשות שפספסתם — AI, טק ותרבות",
     "url": "https://open.spotify.com/show/0R8OGY0eb6BJSepIApWB0z",
     "platform": "spotify", "lang": "he"},
    {"name": "פשוט AI", "name_he": "פשוט AI",
     "desc": "AI explained in simple Hebrew — by Benny Farber",
     "desc_he": "בינה מלאכותית בשפה פשוטה — בני פרבר",
     "url": "https://open.spotify.com/show/3nmpfA2evHKSVvzOnbmb0w",
     "platform": "spotify", "lang": "he"},
    {"name": "בינה בקטנה", "name_he": "בינה בקטנה",
     "desc": "5-min weekly AI news recap — Shira Weinberg Harel",
     "desc_he": "סיכום שבועי של 5 דקות — שירה וינברג הראל",
     "url": "https://open.spotify.com/show/0NnB7UQUMBjx5n24FDE4Iz",
     "platform": "spotify", "lang": "he"},
    {"name": "בינה מלאכותית בגובה העיניים", "name_he": "בינה מלאכותית בגובה העיניים",
     "desc": "AI for everyone — Bar Shaltiel & Yuval Bialik",
     "desc_he": "AI לכולם — בר שאלתיאל ויובל ביאליק",
     "url": "https://open.spotify.com/show/5bt0qGN6KIFkrH3kg5hw5J",
     "platform": "spotify", "lang": "he"},
    {"name": "Hands-On AI", "name_he": "Hands-On AI",
     "desc": "AI in Israeli organizations — by Eyal Marcus",
     "desc_he": "AI בארגונים ישראליים — אייל מרקוס",
     "url": "https://open.spotify.com/show/5ShlAGb2ExK4UwWcN1fkNO",
     "platform": "spotify", "lang": "he"},
    # ── Podcasts — English ─────────────────────────
    {"name": "The AWS Developers Podcast", "name_he": "The AWS Developers Podcast",
     "desc": "AWS services, AI agents, serverless & cloud dev",
     "desc_he": "שירותי AWS, סוכני AI, serverless ופיתוח ענן",
     "url": "https://open.spotify.com/show/7rQjgnBvuyr18K03tnEHBI",
     "platform": "spotify", "lang": "en"},
    {"name": "Lex Fridman Podcast", "name_he": "Lex Fridman Podcast",
     "desc": "Deep conversations with AI leaders & researchers",
     "desc_he": "שיחות מעמיקות עם מובילי AI וחוקרים",
     "url": "https://open.spotify.com/show/2MAi0BvDc6GTFvKFPXnkCL",
     "platform": "spotify", "lang": "en"},
    {"name": "Hard Fork", "name_he": "Hard Fork",
     "desc": "NYT podcast on AI, tech & the internet — fun & sharp",
     "desc_he": "פודקאסט ניו יורק טיימס על AI, טק והאינטרנט",
     "url": "https://open.spotify.com/show/44fllCS2FTFr2x2kjP9xeT",
     "platform": "spotify", "lang": "en"},
]


def youtube_channels() -> list[dict]:
    return [c for c in CHANNELS if c["platform"] == "youtube"]


def podcasts() -> list[dict]:
    return [c for c in CHANNELS if c["platform"] == "spotify"]
